animalbreed_index:
    path:     /
    defaults: { _controller: "AppBundle:AnimalBreed:index" }
    methods:  GET

animalbreed_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:AnimalBreed:show" }
    methods:  GET

animalbreed_new:
    path:     /new
    defaults: { _controller: "AppBundle:AnimalBreed:new" }
    methods:  [GET, POST]

animalbreed_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:AnimalBreed:edit" }
    methods:  [GET, POST]

animalbreed_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:AnimalBreed:delete" }
    methods:  DELETE
