animalhabitat_index:
    path:     /
    defaults: { _controller: "AppBundle:AnimalHabitat:index" }
    methods:  GET

animalhabitat_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:AnimalHabitat:show" }
    methods:  GET

animalhabitat_new:
    path:     /new
    defaults: { _controller: "AppBundle:AnimalHabitat:new" }
    methods:  [GET, POST]

animalhabitat_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:AnimalHabitat:edit" }
    methods:  [GET, POST]

animalhabitat_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:AnimalHabitat:delete" }
    methods:  DELETE
