cage_index:
    path:     /
    defaults: { _controller: "AppBundle:Cage:index" }
    methods:  GET

cage_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cage:show" }
    methods:  GET

cage_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cage:new" }
    methods:  [GET, POST]

cage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cage:edit" }
    methods:  [GET, POST]

cage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cage:delete" }
    methods:  DELETE
